project:
  type: book


book:
  title: "My demo notebook"
  author: "Andrew D. Nguyen"
  date: "2025-04-19"
  
  chapters: 
    - index.qmd
    - part: "Causal inference section"
      chapters:
        - 08_causal_inference_simulations.qmd
    - part: "Misc Bayesian statistics"
      chapters:
        - 13_Bayesian_inference_Beta_priors_JingchenHu_lab1.qmd
    - part: "Misc Frequentist statistics"
      chapters:
        - 14_simulating_95CI_frequentist.qmd
    - part: "Function-valued traits"
      chapters:
      
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

