---
title: "Vignettes in R and reference code"
author: "Andrew D. Nguyen, Quantitative Biologist"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    collapsed: no
    smooth_scroll: no
    css: bootstrap_pulse.css
editor_options: 
  chunk_output_type: console
---

I enjoy learning different analyses and interesting ways to show results. I hope this page will serve as a useful reference!

# Data wrangling, visualization, and statistics in R:     

* *[tidyverse demo](ggplot.pdf)* from a fruit fly dataset and features survival analysis and machine learning with SVM    
* [SQL and R demo](SQL_demo.pdf)- learning how to connect R with a SQL database and building my own SQL database    

* [Making maps](RasterPCA_demo.html) in R and performing PCA on climate rasters and a [leaflet demo](Leaflet_code.html) for making interactive maps


# Exploring [Kaggle](https://www.kaggle.com/) datasets:   

Kaggle has a wealth of datasets for data scientists to explore different analyses.   

* [Breast Cancer](breast_cancer.pdf) survival analysis  
* Stroke Prediction [dataset](https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset?resource=download), [exploratory analyses](stroke.pdf)   


# Decision making under uncertainty:   

* Vignette on the general application of [Dempster-Shafer Theory](DSTmodel_uncertainty.pdf) for decision making       
* My [shinyapp](https://antdrewdnguyen.shinyapps.io/dempster_shafer/) for binary classification using Dempster-Shafer Theory (DST). This specific use case of DST accounts for model uncertainty for predictions and then combining different sources of evidence. 

# Simulations: traits as functions   

A lot of my PhD was spent thinking about understanding complex characteristics of any organism. Often times, traits can change across an environmental gradient and can be represented as a function. To understand traits as functions, I've conducted a few simulations in the area of temperature stress from genes, proteins, to whole organisms. 

* [Simulating performance curves of genetic clones](2018-01-10_simulate_perf_curves.html) and understanding potential evolutionary trajectories using a statistical genetics approach 

* [Simulating the metabolic rates of diapausing animals](2018-01-10_phases_of_diapause_exit.html)   
 
 
* [Fitting boltzmann curves to transcript abundance data](Function_valued_traits.html)       

* [Fitting protein unfolding curves](20170411_prelim_analyses_pog_aph_proteomics.html)      
    * Simulating unfolding parameters and interpreting their biological significance: [Unfolding curve parameter tweaks](2020-03-12_unfolding_curves.html)     



# Unpublished projects:   

* Surveyed ants for stress markers (gene expression) that were exposed to [experimental warming in nature](20170508_stressed_ants_report_forSHC_NJG.html)  
    * Script starts from calculating log2 fold change in gene expression to statistical models to predicting stress back out into nature.   


[Back to main page](https://adnguyen.github.io/)

---------



